"""Initial tables

Revision ID: 2f8b2b83730d
Revises: 
Create Date: 2026-01-03 19:12:47.245101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f8b2b83730d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_retail', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('chollo_score', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', title || ' ' || coalesce(description, ''))", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_content_hash'), 'deals', ['content_hash'], unique=True)
    op.create_index('ix_deals_search_vector', 'deals', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('raw_messages',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'msg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_messages')
    op.drop_index('ix_deals_search_vector', table_name='deals', postgresql_using='gin')
    op.drop_index(op.f('ix_deals_content_hash'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
