"""add_deal_columns

Revision ID: 9528ecba03ef
Revises: 2f8b2b83730d
Create Date: 2026-01-03 23:49:54.866266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9528ecba03ef'
down_revision: Union[str, None] = '2f8b2b83730d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('shop', sa.String(length=100), nullable=True))
    op.add_column('deals', sa.Column('price_before', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('deals', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('deals', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'raw_text')
    op.drop_column('deals', 'source')
    op.drop_column('deals', 'price_before')
    op.drop_column('deals', 'shop')
    # ### end Alembic commands ###
