"""Add discount_percentage to deals

Revision ID: f23685747e04
Revises: 9528ecba03ef
Create Date: 2026-01-17 15:52:51.717860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23685747e04'
down_revision: Union[str, None] = '9528ecba03ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('discount_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'discount_percentage')
    # ### end Alembic commands ###
